### ISSUE TITLE
[orgmode]What about CSS for TOC (table of contents)?

### ISSUE THREAD

**Issue by touxstone** [getnikola/plugins#357]
Hi, I was trying with some themes (e.g. `hyde`) but happening also with others so I miss CSS rules for `toc`. Would anyone know to give a clue about where to make changes so shown `toc` per instance with the ruling below:

 ```css
    /* ToC */
    #toc {
	float: right;
	padding: 0 1rem 1rem 1rem;
	border-left: 1px solid #eee;
	font-size: 0.9rem;
   }
    nav#TableOfContents li {
	padding-bottom: 0.25rem;
   }
   .toc-label {
	font-size: 0.8rem;
	color: #aeaeae;
    }
```
