### ISSUE TITLE
Continuous Import does not generate a slug

### ISSUE THREAD

**Issue by devilgate** [getnikola/plugins#401]
The `continuous_import` plugin doesn't include a slug in the metadata it writes. That is, instead of something like:

```
.. slug: my-latest-post
```

you just get:

```
.. slug:
```

With the standard metadata, that doesn't seem to matter, and a slug is generated from the title at build time. But I recently switched to using YAML for my metadata, and I end up with something like this:

```yaml
---
category: ''
date: Sun, 24 Oct 2021 18:54:02 +0100
description: ''
link: ''
slug: ''
tags: films, letterboxd
title: No Country for Old Men, 2007 - ★★½
type: text
---
```

Trouble is, I do _not_ then get a slug generated from the title at build. Instead the output file is generated as `index.html`. Which works for the first one, but as soon as there's a second, we have a problem.

Oddly, if I _delete_ the `slug:` line, it works. So the problem is perhaps in the main code, with how it's parsing YAML metadata. But I feel that the root of it is that the plugin doesn't create the slug.

Arguably both should be fixed, of course.
